version: '3'
services:
  spacy:
    # Build the Docker image for the app service using the Dockerfile in the ./spaCy directory.
    build:
      context: ./spaCy
      dockerfile: Dockerfile.spacy
    container_name: entity_extraction
    # Map port 5000 in the container to port 5000 on the host machine.
    ports:
      - "5003:5003"
    networks:
      - chatbotnetwork
    hostname: spacy-container
    volumes:
      - ./spaCy:/spacy
  spacytests:
    build:
      context: ./spaCy
      dockerfile: Dockerfile.tests
    volumes:
      - ./spaCy:/spacy
  knowledge_retriever:
    # Build the Docker image for the knowledge_retriever container service using the Dockerfile in the ./knowledge_retriever directory
    build: ./KnowledgeRetriever
    container_name: knowledge_retriever
    ports:
      - "5001:5001"
    networks:
      - chatbotnetwork
    # Link the knowledge_retriever service to the spaCy service. Allows the knowledge_retriever service to communicate with the spaCy service
    links:
      - spacy
      - api_connect
      - llama
    volumes:
      - ./KnowledgeRetriever:/knowledge_retriever
  api_connect:
    # Build the Docker image for the app service using the Dockerfile in the ./spaCy directory.
    build:
      context: ./API_Connections
    container_name: api_connections
    # Map port 5002 in the container to port 5002 on the host machine.
    ports:
      - "5002:5002"
    networks:
      - chatbotnetwork
    hostname: api-container
    volumes:
      - ./API_Connections:/api_connections
  llama:
    image: eshes/knox-group-g:master_llama
    container_name: llama_prod
    ports:
      - "5004:5004"
    networks:
      - chatbotnetwork
    hostname: llama-container
networks:
  chatbotnetwork: