version: '3'
services:
  spacy:
    # Get the Docker image for the app service using the Dockerfile in the ./spaCy directory.
    image: eshes/knox-group-g:Master_spaCy
    container_name: entity_extraction_prod
    # Map port 5003 in the container to port 5003 on the host machine.
    ports:
      - "5003:5003"
    networks:
      - chatbotnetwork
    hostname: spacy-container
  knowledge_retriever:
    # Get the Docker image for the knowledge_retriever container service using the Dockerfile in the ./knowledge_retriever directory
    image: eshes/knox-group-g:Master_KnowledgeRetriever
    container_name: knowledge_retriever_prod
    ports:
      - "5001:5001"
    networks:
      - chatbotnetwork
    # Link the knowledge_retriever service to the spaCy and API service. Allows the knowledge_retriever service to communicate with the spaCy service
    links:
      - spacy
      - api_connect
  api_connect:
    # Build the Docker image for the app service using the Dockerfile in the ./API_Connections directory.
    image: eshes/knox-group-g:Master_ApiConnect
    container_name: api_connections_prod
    # Map port 5002 in the container to port 5002 on the host machine.
    ports:
      - "5002:5002"
    networks:
      - chatbotnetwork
    hostname: api-container
  llama:
    image: eshes/knox-group-g:Master_Llama
    container_name: llama_prod
    ports:
      - "5004:5004"
    networks:
      - chatbotnetwork
    hostname: llama-container
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 300
    environment:
      WATCHTOWER_CLEANUP: 'true'
networks:
  chatbotnetwork:
