version: '3'
services:
  spacy:
    # Build the Docker image for the app service using the Dockerfile in the ./spaCy directory.
    build: ./spacy
    # Map port 5000 in the container to port 5000 on the host machine.
    ports:
      - "5000:5000"
  knowledge_retriever:
    # Build the Docker image for the knowledge_retriever container service using the Dockerfile in the ./knowledge_retriever directory
    build: ./knowledge_retriever
    ports:
      - "5001:5000"
    # Link the knowledge_retriever service to the spaCy service. Allows the knowledge_retriever service to communicate with the spaCy service
    links:
      - spacy