version: '3'
services:
  spacy:
    # Get the Docker image for the app service using the Dockerfile in the ./spaCy directory.
    image: eshes/knox-group-g:Master_spaCy
    container_name: entity_extraction_prod
    # Map port 5000 in the container to port 5000 on the host machine.
    ports:
      - "5000:5000"
    networks:
      - chatbotnetwork
    hostname: spacy-container
  knowledge_retriever:
    # Get the Docker image for the knowledge_retriever container service using the Dockerfile in the ./knowledge_retriever directory
    image: eshes/knox-group-g:Master_KnowledgeRetriever
    container_name: knowledge_retriever_prod
    ports:
      - "5001:5001"
    networks:
      - chatbotnetwork
    # Link the knowledge_retriever service to the spaCy service. Allows the knowledge_retriever service to communicate with the spaCy service
    links:
      - spacy
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 300
    environment:
      WATCHTOWER_CLEANUP: eshes/knox-group-g:Master_spaCy,eshes/knox-group-g:Master_KnowledgeRetriever
networks:
  chatbotnetwork: